controller_joint_names: ['', 'FR_Hip0_joint', 'FR_Hip1_joint', 'FR_Hip2_joint', 'FL_Hip3_joint', 'FL_Hip4_joint', 'FL_Hip5_joint', 'RR_Hip6_joint', 'RR_Hip7_joint', 'RR_Hip8_joint', 'RL_Hip9_joint', 'RL_Hip10_joint', 'RL_Hip11_joint', ]
